---
synced_folders:
  vagrant:
    from: '.'
    to: '/vagrant'
    options:
      :nfs: true

boxes:
  lemp:
    box_name: 'ubuntu/trusty64'
    hostname: 'lemp.local'
    ip: 192.168.13.11
    synced_folders:
      lemp:
        from: '.'
        to: '/var/www/lemp'
        options:
          :nfs: true
          :mount_options: ['vers=3', 'udp', 'actimeo=1']
    provisioners:
      shell:
        lemp:
          path: 'shell/lemp.sh'
    memory: 1024
    cpus:   2
